export const portfolioData = {
  profile: {
    name: 'Fathan Imaad',
    eyebrow: 'Final-year Psychology student',
    email: 'fathanimaad@gmail.com',
    linkedin: 'https://www.linkedin.com/in/fathan-imaad/',
    resumePath: '/fathan-imaad-cv.pdf',
  },
  navigation: [
    { label: 'About', href: '#about' },
    { label: 'Experience', href: '#experience' },
    { label: 'Academic', href: '#academic' },
    { label: 'Skills', href: '#skills' },
    { label: 'Training', href: '#training' },
    { label: 'Interests', href: '#interests' },
    { label: 'Contact', href: '#contact' },
  ],
  hero: {
    summary:
      'Final-year Psychology student with experience in academic research, community operations, collaboration management, data handling, and structured communication.',
    direction:
      'I am interested in work involving people, communication, coordination, research, organization, and structured problem-solving.',
    highlights: [
      {
        value: '100+',
        label: 'Collaboration opportunities coordinated',
        note: 'Across two volunteer communities',
      },
      {
        value: '5–7',
        label: 'Academic team members typically coordinated',
        note: 'Across Psychology and research courses',
      },
      {
        value: '2022–2024',
        label: 'Volunteer professional experience',
        note: 'International online environment',
      },
    ],
  },
  areasOfInterest: [
    'Human Resources',
    'Recruitment & Talent Acquisition',
    'Human Capital / People Operations',
    'Operations',
    'Administration',
    'Research',
    'Community Operations',
    'Partnerships',
  ],
  volunteerExperience: [
    {
      organization: 'Stress Capital',
      role: 'Collaboration Manager',
      period: '2024',
      type: 'Volunteer',
      bullets: [
        'Independently researched and evaluated potential external collaboration partners.',
        'Reviewed publicly available information to identify credibility concerns and potential risk indicators.',
        'Conducted professional written outreach and negotiations in English.',
        'Decided whether routine collaboration opportunities should proceed based on available information and defined responsibilities.',
        'Coordinated participant information, requirements, deadlines, and follow-up with external partners.',
        'Escalated requests involving official organizational communications when they fell outside my authority.',
      ],
    },
    {
      organization: 'Chillchat Pte. Ltd.',
      role: 'Collaboration Manager',
      period: '2023–2024',
      type: 'Volunteer',
      bullets: [
        'Researched potential external partners and identified suitable collaboration opportunities.',
        'Conducted written outreach and negotiations in English with project representatives.',
        'Communicated the community value proposition and discussed mutually beneficial arrangements.',
        'Coordinated agreed requirements, participant information, deadlines, and responsibilities between parties.',
        'Managed participant access processes and submitted required information to partner teams.',
        'Maintained follow-up communication and resolved eligibility or coordination issues when necessary.',
        'Managed multiple collaboration activities simultaneously while working within deadlines.',
      ],
    },
    {
      organization: 'Chillchat Pte. Ltd.',
      role: 'Community Moderator',
      period: '2022–2024',
      type: 'Volunteer',
      bullets: [
        'Supported an international online community by responding to member questions and providing day-to-day assistance.',
        'Used English as the primary language for written communication with international community members.',
        'Moderated discussions and handled disruptive behavior while allowing constructive criticism and differing opinions.',
        'Escalated complex project-related questions and issues to the appropriate team members when they were outside moderator authority.',
        'Worked alongside approximately five other moderators to handle community issues and support ongoing activities.',
        'Assisted with event-related questions, support requests, and issue resolution.',
        'Helped maintain an organized and safe online community environment.',
      ],
    },
  ],
  workflow: [
    { title: 'Discover', description: 'Identify opportunities through requests, referrals, or independent research.' },
    { title: 'Research', description: 'Review publicly available information and assess suitability.' },
    { title: 'Outreach', description: 'Contact relevant project representatives.' },
    { title: 'Negotiate', description: 'Discuss collaboration value, requirements, responsibilities, and constraints.' },
    { title: 'Confirm', description: 'Finalize expectations, participant requirements, and deadlines.' },
    { title: 'Coordinate', description: 'Manage participant information and agreed activities.' },
    { title: 'Verify', description: 'Confirm that required information has been received and processed correctly.' },
    { title: 'Resolve', description: 'Follow up when participant or coordination issues arise.' },
  ],
  academicProjects: [
    {
      index: '01',
      title: 'Job Analysis & Job Description Development',
      summary:
        'An academic project combining interviews, document review, information organization, and structured role documentation.',
      bullets: [
        'Collected role-related information through interviews and document review.',
        'Organized findings into structured job information.',
        'Developed job descriptions and job specifications based on collected information.',
        'Coordinated report preparation with team members.',
        'Reviewed accuracy, structure, consistency, and formatting before submission.',
        'Completed the project within academic deadlines.',
      ],
      areas: ['Interviewing', 'Documentation', 'Information Organization', 'Team Coordination', 'Report Preparation'],
    },
    {
      index: '02',
      title: 'Quantitative Research',
      summary:
        'Structured academic research involving data collection, organization, analysis, and report preparation.',
      bullets: [
        'Participated in quantitative research involving data collection, organization, analysis, and report preparation.',
        'Coordinated activities with team members throughout the research process.',
        'Processed structured data using Microsoft Excel and IBM SPSS.',
        'Maintained confidentiality of respondent information.',
        'Prepared structured tables and academic reports.',
      ],
      areas: ['Data Organization', 'Excel', 'IBM SPSS', 'Confidentiality', 'Reporting'],
    },
    {
      index: '03',
      title: 'Qualitative Research & Interviewing',
      summary:
        'Academic interviewing and qualitative data collection organized into structured findings and reports.',
      bullets: [
        'Conducted academic interviews and qualitative data collection.',
        'Organized collected information into structured findings.',
        'Maintained confidentiality of respondent information.',
        'Coordinated report preparation with team members.',
      ],
      areas: ['Interviewing', 'Communication', 'Confidentiality', 'Documentation', 'Research'],
    },
    {
      index: '04',
      title: 'Psychological Scale Development & Measurement Instrument Construction',
      summary:
        'Academic exposure to structured research processes, documentation, data organization, teamwork, and report preparation.',
      bullets: [],
      areas: ['Research Process', 'Data Organization', 'Documentation', 'Teamwork', 'Report Preparation'],
    },
  ],
  skillCategories: [
    {
      category: 'Communication & Coordination',
      secondary: false,
      items: [
        'Professional Written English Communication',
        'Stakeholder Communication',
        'Negotiation',
        'Outreach',
        'Follow-up',
        'Issue Handling',
        'Team Coordination',
        'Escalation Judgment',
      ],
    },
    {
      category: 'Research & Data',
      secondary: false,
      items: [
        'Quantitative Research',
        'Qualitative Research',
        'Interviewing',
        'Data Organization',
        'Microsoft Excel',
        'IBM SPSS',
      ],
    },
    {
      category: 'Documentation & Productivity',
      secondary: false,
      items: [
        'Microsoft Word',
        'Microsoft PowerPoint',
        'Google Docs',
        'Google Sheets',
        'Structured Report Preparation',
        'Digital Documentation',
      ],
    },
    {
      category: 'Digital Communication',
      items: ['Discord', 'X / Twitter', 'Telegram'],
      secondary: true,
    },
  ],
  excelSkills: [
    'SUM',
    'AVERAGE',
    'COUNT',
    'COUNTIF',
    'IF',
    'OR',
    'VLOOKUP',
    'XLOOKUP',
    'LEFT',
    'MID',
    'RIGHT',
    'CONCAT',
    'MAX',
    'MIN',
    'Sort',
    'Filter',
    'Basic PivotTables',
  ],
  languages: [
    {
      language: 'Indonesian',
      level: 'Native',
      context: 'Primary everyday and academic language.',
    },
    {
      language: 'English',
      level: 'Professional Working Proficiency',
      context:
        'Regularly used for written communication with international community members and external project representatives, including outreach, negotiation, clarification, coordination, and follow-up.',
    },
  ],
  training: [
    { title: 'Recruitment and Selection Process Training', institution: 'Universitas Gunadarma', year: '2025' },
    { title: 'Training on Preparing and Managing Job Descriptions & SOP HRM', institution: 'Universitas Gunadarma', year: '2024' },
    { title: 'Training on Final Recruitment Process & Employee Orientation', institution: 'Universitas Gunadarma', year: '2025' },
    { title: 'Training on Learning and Human Resource Development', institution: 'Universitas Gunadarma', year: '2025' },
    { title: 'Training on Learning & Development Needs & Organizational Structure', institution: 'Universitas Gunadarma', year: '2024' },
  ],
  education: {
    institution: 'Universitas Gunadarma',
    degree: 'Bachelor of Psychology',
    period: '2022–Present',
    expectedGraduation: '2026',
    gpa: '3.68 / 4.00',
    status: 'Completed all regular coursework and currently focusing on undergraduate thesis.',
    exposure: [
      'Job Analysis',
      'Interviewing',
      'Quantitative Research',
      'Qualitative Research',
      'Psychological Scale Development',
      'Measurement Instrument Construction',
      'Statistics',
    ],
  },
} as const;
